/*
Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/elasticdeeplearning/trainingjob-operator/pkg/apis/aitrainingjob/v1"
	scheme "github.com/elasticdeeplearning/trainingjob-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AITrainingJobsGetter has a method to return a AITrainingJobInterface.
// A group's client should implement this interface.
type AITrainingJobsGetter interface {
	AITrainingJobs(namespace string) AITrainingJobInterface
}

// AITrainingJobInterface has methods to work with AITrainingJob resources.
type AITrainingJobInterface interface {
	Create(*v1.AITrainingJob) (*v1.AITrainingJob, error)
	Update(*v1.AITrainingJob) (*v1.AITrainingJob, error)
	UpdateStatus(*v1.AITrainingJob) (*v1.AITrainingJob, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AITrainingJob, error)
	List(opts metav1.ListOptions) (*v1.AITrainingJobList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AITrainingJob, err error)
	AITrainingJobExpansion
}

// aITrainingJobs implements AITrainingJobInterface
type aITrainingJobs struct {
	client rest.Interface
	ns     string
}

// newAITrainingJobs returns a AITrainingJobs
func newAITrainingJobs(c *ElasticdeeplearningV1Client, namespace string) *aITrainingJobs {
	return &aITrainingJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aITrainingJob, and returns the corresponding aITrainingJob object, and an error if there is any.
func (c *aITrainingJobs) Get(name string, options metav1.GetOptions) (result *v1.AITrainingJob, err error) {
	result = &v1.AITrainingJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AITrainingJobs that match those selectors.
func (c *aITrainingJobs) List(opts metav1.ListOptions) (result *v1.AITrainingJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AITrainingJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aITrainingJobs.
func (c *aITrainingJobs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a aITrainingJob and creates it.  Returns the server's representation of the aITrainingJob, and an error, if there is any.
func (c *aITrainingJobs) Create(aITrainingJob *v1.AITrainingJob) (result *v1.AITrainingJob, err error) {
	result = &v1.AITrainingJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		Body(aITrainingJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a aITrainingJob and updates it. Returns the server's representation of the aITrainingJob, and an error, if there is any.
func (c *aITrainingJobs) Update(aITrainingJob *v1.AITrainingJob) (result *v1.AITrainingJob, err error) {
	result = &v1.AITrainingJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		Name(aITrainingJob.Name).
		Body(aITrainingJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *aITrainingJobs) UpdateStatus(aITrainingJob *v1.AITrainingJob) (result *v1.AITrainingJob, err error) {
	result = &v1.AITrainingJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		Name(aITrainingJob.Name).
		SubResource("status").
		Body(aITrainingJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the aITrainingJob and deletes it. Returns an error if one occurs.
func (c *aITrainingJobs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aITrainingJobs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aitrainingjobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched aITrainingJob.
func (c *aITrainingJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AITrainingJob, err error) {
	result = &v1.AITrainingJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("aitrainingjobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
