/*
Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aitrainingjobv1 "github.com/elasticdeeplearning/trainingjob-operator/pkg/apis/aitrainingjob/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAITrainingJobs implements AITrainingJobInterface
type FakeAITrainingJobs struct {
	Fake *FakeElasticdeeplearningV1
	ns   string
}

var aitrainingjobsResource = schema.GroupVersionResource{Group: "elasticdeeplearning.ai", Version: "v1", Resource: "aitrainingjobs"}

var aitrainingjobsKind = schema.GroupVersionKind{Group: "elasticdeeplearning.ai", Version: "v1", Kind: "AITrainingJob"}

// Get takes name of the aITrainingJob, and returns the corresponding aITrainingJob object, and an error if there is any.
func (c *FakeAITrainingJobs) Get(name string, options v1.GetOptions) (result *aitrainingjobv1.AITrainingJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aitrainingjobsResource, c.ns, name), &aitrainingjobv1.AITrainingJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aitrainingjobv1.AITrainingJob), err
}

// List takes label and field selectors, and returns the list of AITrainingJobs that match those selectors.
func (c *FakeAITrainingJobs) List(opts v1.ListOptions) (result *aitrainingjobv1.AITrainingJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aitrainingjobsResource, aitrainingjobsKind, c.ns, opts), &aitrainingjobv1.AITrainingJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aitrainingjobv1.AITrainingJobList{ListMeta: obj.(*aitrainingjobv1.AITrainingJobList).ListMeta}
	for _, item := range obj.(*aitrainingjobv1.AITrainingJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aITrainingJobs.
func (c *FakeAITrainingJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aitrainingjobsResource, c.ns, opts))

}

// Create takes the representation of a aITrainingJob and creates it.  Returns the server's representation of the aITrainingJob, and an error, if there is any.
func (c *FakeAITrainingJobs) Create(aITrainingJob *aitrainingjobv1.AITrainingJob) (result *aitrainingjobv1.AITrainingJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aitrainingjobsResource, c.ns, aITrainingJob), &aitrainingjobv1.AITrainingJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aitrainingjobv1.AITrainingJob), err
}

// Update takes the representation of a aITrainingJob and updates it. Returns the server's representation of the aITrainingJob, and an error, if there is any.
func (c *FakeAITrainingJobs) Update(aITrainingJob *aitrainingjobv1.AITrainingJob) (result *aitrainingjobv1.AITrainingJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aitrainingjobsResource, c.ns, aITrainingJob), &aitrainingjobv1.AITrainingJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aitrainingjobv1.AITrainingJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAITrainingJobs) UpdateStatus(aITrainingJob *aitrainingjobv1.AITrainingJob) (*aitrainingjobv1.AITrainingJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(aitrainingjobsResource, "status", c.ns, aITrainingJob), &aitrainingjobv1.AITrainingJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aitrainingjobv1.AITrainingJob), err
}

// Delete takes name of the aITrainingJob and deletes it. Returns an error if one occurs.
func (c *FakeAITrainingJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(aitrainingjobsResource, c.ns, name), &aitrainingjobv1.AITrainingJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAITrainingJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aitrainingjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aitrainingjobv1.AITrainingJobList{})
	return err
}

// Patch applies the patch and returns the patched aITrainingJob.
func (c *FakeAITrainingJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aitrainingjobv1.AITrainingJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aitrainingjobsResource, c.ns, name, pt, data, subresources...), &aitrainingjobv1.AITrainingJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aitrainingjobv1.AITrainingJob), err
}
