/*
Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	aitrainingjobv1 "github.com/elasticdeeplearning/trainingjob-operator/pkg/apis/aitrainingjob/v1"
	versioned "github.com/elasticdeeplearning/trainingjob-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/elasticdeeplearning/trainingjob-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/elasticdeeplearning/trainingjob-operator/pkg/client/listers/aitrainingjob/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AITrainingJobInformer provides access to a shared informer and lister for
// AITrainingJobs.
type AITrainingJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AITrainingJobLister
}

type aITrainingJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAITrainingJobInformer constructs a new informer for AITrainingJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAITrainingJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAITrainingJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAITrainingJobInformer constructs a new informer for AITrainingJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAITrainingJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticdeeplearningV1().AITrainingJobs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticdeeplearningV1().AITrainingJobs(namespace).Watch(options)
			},
		},
		&aitrainingjobv1.AITrainingJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *aITrainingJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAITrainingJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aITrainingJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&aitrainingjobv1.AITrainingJob{}, f.defaultInformer)
}

func (f *aITrainingJobInformer) Lister() v1.AITrainingJobLister {
	return v1.NewAITrainingJobLister(f.Informer().GetIndexer())
}
